
version: '3'
services:  
app:    
build: .   
 ports: 
      - "3000:3000"
          environment: 
               - DB_USER=${DB_USER}
                     - DB_PASS=${DB_PASS}
                           - DB_NAME=${DB_NAME}
                                 - DB_HOST=db  
                                     - JWT_SECRET=${JWT_SECRET}
                                         depends_on:
                                               - db  db:
                                                   image: postgres
                                                       environment: 
                                                            POSTGRES_USER: ${DB_USER}
                                                                  POSTGRES_PASSWORD: ${DB_PASS}
                                                                        POSTGRES_DB: ${DB_NAME}
                                                                            ports:      - "5432:5432"